licensePlate: e4ca1d
users:
  - name: zorin.samji@gov.bc.ca
    role: ROLE_TEAM_MANAGER
  - name: arcshiftsolutions@gmail.com
    role: ROLE_TEAM_MANAGER
  - name: jonathan.sharman@gov.bc.ca
    role: ROLE_TEAM_MANAGER
  - name: tzhang200@gmail.com
    role: ROLE_TEAM_MANAGER
  - name: nithinshekar.kuruba@gov.bc.ca
    role: ROLE_TEAM_MANAGER
  - name: bcgov.sso@gov.bc.ca
    role: ROLE_TEAM_MANAGER
  - name: jonathan.langlois@gov.bc.ca
    role: ROLE_TEAM_MANAGER
